// Generated by scripts/package-cricheroes-extension.mjs — do not edit by hand.
export const CRICHEROES_EXTENSION = {
  hash: 'a0fea5dbaebcebb8',
  url: 'https://firebasestorage.googleapis.com/v0/b/e-auction-store.firebasestorage.app/o/downloads%2Fcricheroes-live-sync-a0fea5dbaebcebb8.zip?alt=media&token=918589d9-0ac7-423b-b8b4-317c980133e1',
} as const;
