// All available player stat fields that can be toggled
export const ALL_PLAYER_STAT_FIELDS = [
  { key: 'age', label: 'Age' },
  { key: 'matches', label: 'Matches' },
  { key: 'runs', label: 'Runs' },
  { key: 'wickets', label: 'Wickets' },
  { key: 'battingBestFigures', label: 'Highest Score' },
  { key: 'bowlingBestFigures', label: 'Best Bowling' },
  { key: 'battingStats.innings', label: 'Batting Innings' },
  { key: 'battingStats.notOut', label: 'Not Outs' },
  { key: 'battingStats.average', label: 'Batting Average' },
  { key: 'battingStats.strikeRate', label: 'Batting Strike Rate' },
  { key: 'battingStats.thirties', label: '30s' },
  { key: 'battingStats.fifties', label: '50s' },
  { key: 'battingStats.hundreds', label: '100s' },
  { key: 'battingStats.fours', label: 'Fours' },
  { key: 'battingStats.sixes', label: 'Sixes' },
  { key: 'bowlingStats.innings', label: 'Bowling Innings' },
  { key: 'bowlingStats.overs', label: 'Overs Bowled' },
  { key: 'bowlingStats.maidens', label: 'Maidens' },
  { key: 'bowlingStats.wickets', label: 'Bowling Wickets' },
  { key: 'bowlingStats.bestBowling', label: 'Best Bowling Figures' },
  { key: 'bowlingStats.threeWickets', label: '3 Wickets' },
  { key: 'bowlingStats.fiveWickets', label: '5 Wickets' },
  { key: 'bowlingStats.economy', label: 'Economy Rate' },
  { key: 'bowlingStats.strikeRate', label: 'Bowling Strike Rate' },
  { key: 'bowlingStats.average', label: 'Bowling Average' },
] as const;
